version: "3"
services:
  ylz-xyz-ui:
    build:
      dockerfile: Dockerfile.dev
      context: ./ylz-xyz-ui
    volumes:
      - /app/node_modules
      - ./ylz-xyz-ui:/app
    environment:
      - PORT=1000
      - REACT_APP_IAM_SERVICE_URI=ylz-xyz-iam-svc
      - REACT_APP_PROJECT_SERVICE_URI=ylz-xyz-project-svc
      - REACT_APP_DEVICE_SERVICE_URI=ylz-xyz-device-svc
      - REACT_APP_FILE_SERVICE_URI=ylz-xyz-file-svc
  ylz-xyz-iam-svc:
    build:
      dockerfile: Dockerfile.dev
      context: ./ylz-xyz-iam-svc
    volumes:
      - /app/node_modules
      - ./ylz-xyz-iam-svc:/app
    environment:
      - PORT=4000
  ylz-xyz-project-svc:
    build:
      dockerfile: Dockerfile.dev
      context: ./ylz-xyz-project-svc
    volumes:
      - /app/node_modules
      - ./ylz-xyz-project-svc:/app
    environment:
      - PORT:3000
      - IAM_SERVICE_URI=ylz-xyz-iam-svc
      - DEVICE_SERVICE_URI=ylz-xyz-device-svc
      - FILE_SERVICE_URI=ylz-xyz-file-svc
  ylz-xyz-device-svc:
    build:
      dockerfile: Dockerfile.dev
      context: ./ylz-xyz-device-svc
    volumes:
      - /app/node_modules
      - ./ylz-xyz-device-svc:/app
    environment:
      - PORT=5000
  ylz-xyz-file-svc:
    build:
      dockerfile: Dockerfile.dev
      context: ./ylz-xyz-file-svc
    volumes:
      - /app/node_modules
      - ./ylz-xyz-file-svc:/app
    environment:
      - PORT=1000

